-- generated by client-patch/mk_mogit_razagath.pl
-- Register a custom MogIt data module that behaves exactly like a built-in
-- one (Cloth/Leather/...). MogIt sets _G.MogIt = its private table, so every
-- MogIt.base.* helper and MogIt:RegisterModule are reachable from here.
local MogIt = _G.MogIt
if not (MogIt and MogIt.RegisterModule and MogIt.base and MogIt.base.AddSlot) then return end

-- MogIt_Modules_Extra scans every addon with an X-MogItModuleVersion tag and
-- pre-registers it as a browserless stub *before* our data files load; our .toc
-- omits that tag so it should skip us, but if a stub is present anyway, drop it
-- (and its moduleList slot) so RegisterModule builds the real thing.
local stub = MogIt.modules and MogIt.modules["MogIt_Razagath"]
if stub then
    MogIt.modules["MogIt_Razagath"] = nil
    for idx = #MogIt.moduleList, 1, -1 do
        if MogIt.moduleList[idx] == stub then table.remove(MogIt.moduleList, idx) end
    end
end

MogIt:RegisterModule("MogIt_Razagath", MogIt.moduleVersion or 2, {
    label       = "Razagath",
    base        = true,
    slots       = {},
    slotList    = {},
    Dropdown      = MogIt.base.Dropdown,
    BuildList     = MogIt.base.BuildList,
    FrameUpdate   = MogIt.base.FrameUpdate,
    OnEnter       = MogIt.base.OnEnter,
    OnClick       = MogIt.base.OnClick,
    Unlist        = MogIt.base.Unlist,
    Help          = MogIt.base.Help,
    GetFilterArgs = MogIt.base.GetFilterArgs,
    filters = { "name", "level", "itemLevel", "faction", "class", "source",
                "quality", "bind", "chestType", "sheath", "slot", "hasItem" },
    sorting = { "level", "itemLevel", "alpha", "display", "id", "colour" },
    sorts   = { level = MogIt.base.SortLevel, colour = MogIt.base.SortColour },
})
