<#  Pull the freshly built client artifacts out of the mod-razagath-classes
    module into this repo so a release can be cut.

      overlay/Interface/AddOns/SpellBladeUI/SpellBladeUI.lua  <- module client-patch/addon
      patch/patch-enUS-Z.MPQ                                  <- module client-patch

    The game exe is NOT copied here - it is never redistributed. The launcher
    patches the player's own clean Wow.exe in place (see ExePatcher in
    RazagathLauncher.cs). If the five byte offsets ever change, update that table
    and the CleanSha256 / PatchedSha256 constants.
#>
[CmdletBinding()]
param(
    [string]$Module = "C:\Azerothcore\modules\mod-razagath-classes\client-patch"
)
$ErrorActionPreference = "Stop"
$Repo = Split-Path -Parent $PSScriptRoot

# Razagath - the single player-facing UI addon (SpellBlade class registration,
# BigBags, Mounts & Pets window). It replaces the old SpellBladeUI,
# RazagathBigBags and RazagathCompanions folders: those are removed from the
# overlay here, and wiped from players' clients by build-release.ps1's legacy
# member list. (MogIt_Razagath stays its own addon - it is a MogIt plugin.)
$razSrc = "$Module\addon\Razagath"
$razDst = "$Repo\overlay\Interface\AddOns\Razagath"
if (-not (Test-Path $razSrc)) { throw "no Razagath addon in $Module" }
foreach ($legacy in "SpellBladeUI","RazagathBigBags","RazagathCompanions") {
    $p = "$Repo\overlay\Interface\AddOns\$legacy"
    if (Test-Path $p) { Remove-Item $p -Recurse -Force }
}
if (Test-Path $razDst) { Remove-Item $razDst -Recurse -Force }
Copy-Item $razSrc $razDst -Recurse -Force
Write-Host ("synced Razagath  ({0} files)" -f (Get-ChildItem $razDst -Recurse -File).Count)

# MogIt_Razagath - generated custom-item data module for the bundled MogIt.
# (MogIt itself lives directly in overlay/, it is not built from the module.)
$mogitSrc = "$Module\addon\MogIt_Razagath"
$mogitDst = "$Repo\overlay\Interface\AddOns\MogIt_Razagath"
if (Test-Path $mogitSrc) {
    if (Test-Path $mogitDst) { Remove-Item $mogitDst -Recurse -Force }
    Copy-Item $mogitSrc $mogitDst -Recurse -Force
    Write-Host ("synced MogIt_Razagath  ({0} files)" -f (Get-ChildItem $mogitDst -File).Count)
} else {
    Write-Warning "no MogIt_Razagath in $Module - run client-patch/mk_mogit_razagath.pl first"
}


# RazagathGMTools is DELIBERATELY NOT synced here - it's a personal GM dev-
# test tool (quick commands / NPC browser / item spawner) that must never
# reach players, even though the server-side handshake alone would make it
# harmless for a non-GM. Source lives at $Module\addon\RazagathGMTools and
# is deployed by hand straight into the dev client's own Interface\AddOns\ -
# never add a sync block for it here.

if (Test-Path "$Module\patch-enUS-Z.MPQ") {
    Copy-Item "$Module\patch-enUS-Z.MPQ" "$Repo\patch\patch-enUS-Z.MPQ" -Force
    $m = Get-Item "$Repo\patch\patch-enUS-Z.MPQ"
    Write-Host ("synced patch-enUS-Z.MPQ  ({0:N0} bytes)" -f $m.Length)
} else {
    Write-Warning "no patch-enUS-Z.MPQ in $Module - run the module's build_final.pl first"
}

# Root-level Data\Patch-Z.MPQ (CharSections / CreatureModelData / EmotesTextSound ... that the stock root Patch-F/G/H would otherwise override)
if (Test-Path "$Module\.build\Patch-Z.MPQ") {
    Copy-Item "$Module\.build\Patch-Z.MPQ" "$Repo\patch\Patch-Z.MPQ" -Force
    $m = Get-Item "$Repo\patch\Patch-Z.MPQ"
    Write-Host ("synced Patch-Z.MPQ  ({0:N0} bytes)" -f $m.Length)
} else {
    Write-Warning "no .build\Patch-Z.MPQ in $Module - run the module's build_mpq.pl first"
}

# RazagathQuestie - Gilneas quest data for the (separately bundled) Questie-335 add-on; generated by gilneas\gil_questie.py.
$qSrc = "$Module\addon\RazagathQuestie"
$qDst = "$Repo\overlay\Interface\AddOns\RazagathQuestie"
if (Test-Path $qSrc) {
    if (Test-Path $qDst) { Remove-Item $qDst -Recurse -Force }
    Copy-Item $qSrc $qDst -Recurse -Force
    Write-Host ("synced RazagathQuestie  ({0} files)" -f (Get-ChildItem $qDst -File).Count)
} else { Write-Warning "no RazagathQuestie in $Module - run gilneas\gil_questie.py" }

# Root-level Data\Patch-Y.MPQ (Gilneas world data + DBC tables), built by gilneas\pack.sh
if (Test-Path "$Module\gilneas\.build\Patch-Y.MPQ") {
    Copy-Item "$Module\gilneas\.build\Patch-Y.MPQ" "$Repo\patch\Patch-Y.MPQ" -Force
    $m = Get-Item "$Repo\patch\Patch-Y.MPQ"
    Write-Host ("synced Patch-Y.MPQ  ({0:N0} bytes)" -f $m.Length)
} else { Write-Warning "no gilneas\.build\Patch-Y.MPQ in $Module - run gilneas\pack.sh" }
