; generated by tools/stage-client.ps1 - do not edit
!define CLIENT_VERSION "2026.09.04"
!define CLIENT_STEM "RazagathWoW-client-2026.09.04"
!define CLIENT_BASEURL "https://archive.org/download/rzgcw-client-2026-09-04"
!define CLIENT_VOLUMES 9
!define CLIENT_NEED_MB 35888

!macro DOWNLOAD_CLIENT_VOLUMES
  !insertmacro DL_VOLUME 0 "001" "0ba009abb8ff33572f0125577128b55c474ae11e38c564d27b0ead545a7b2229"
  !insertmacro DL_VOLUME 1 "002" "0471f1ea7e7db885531a99fb149817a90fe705f57a4145d2667d7fafea76f8d5"
  !insertmacro DL_VOLUME 2 "003" "cb38988a94c431b296c5fd9d6549515a5f8cd72ddb8ca3fedc9fa827eac21863"
  !insertmacro DL_VOLUME 3 "004" "c93813bf5a2391928afdb310baefea14149dc468dc320999a5a9bfbf0ced077c"
  !insertmacro DL_VOLUME 4 "005" "a7dbe987c4442555f5184a4a969c3aa068a1d68ee4ae5ce94fdeb227fb5cd9a5"
  !insertmacro DL_VOLUME 5 "006" "b9c844926a7787660fca666079e7f39390092d5c5bbdb20771a3f5fe6ed77308"
  !insertmacro DL_VOLUME 6 "007" "68a569e62fe9de42fa2b2fde0b9dbb47a65d0c25b6f1e13e67d9f1f901eaecbe"
  !insertmacro DL_VOLUME 7 "008" "48aadafe78b2f4e11363cb921861c3a156ac857c0375bbdcb21a819d7ceb4a48"
  !insertmacro DL_VOLUME 8 "009" "755ac0cb49ac8b08d557efbdf86c9d2ceff6893324c92dfaab53224c7f090199"
!macroend
